language: java
jdk:
- oraclejdk8
install: true
script: mvn clean install
before_install:
- openssl aes-256-cbc -K $encrypted_75337311b143_key -iv $encrypted_75337311b143_iv
  -in test.txt.enc -out test.txt -d
