language: java
jdk:
- oraclejdk8
install: true
script: mvn clean install
before_install:
- openssl aes-256-cbc -K $encrypted_959daf992838_key -iv $encrypted_959daf992838_iv
  -in App.java.enc -out App.java -d
