language: cpp
compiler: clang
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - python3
        - libstdc++-4.8-dev
install: true
#script: ./critic test
script: ./configure && make && make test
