language: java
jdk:
- oraclejdk8
install: true
script: mvn clean install
before_install:
- openssl enc -aes-256-cbc -d -in test.txt.enc -out test.txt -base64 -K $encrypted_d1234_key -iv $encrypted_d1234_iv
